name: Migrate DB and Trigger Vercel Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  migrate-and-deploy:
    name: Prisma migrate deploy → Vercel deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma migrate deploy (production)
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.PROD_DIRECT_URL }}
        run: npx prisma migrate deploy

      - name: Trigger Vercel Deploy Hook (optional)
        if: ${{ secrets.VERCEL_DEPLOY_HOOK != '' }}
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          echo "POST $HOOK"
          curl -sS -X POST "$HOOK" -H 'Content-Type: application/json' -d '{"source":"github-actions"}'


